---
- name: Create a directory
  ansible.builtin.file:
    path: "addon"
    state: directory
    mode: "0755"

- name: Download firefox addons
  ansible.builtin.get_url:
    url: "{{ item }}"
    dest: "addon/"
    mode: "0644"
  loop:
    - "https://addons.mozilla.org/firefox/downloads/latest/user-agent-string-switcher/latest.xpi"
    - "https://addons.mozilla.org/firefox/downloads/latest/foxyproxy-standard/latest.xpi"
    - "https://addons.mozilla.org/firefox/downloads/latest/deepl-translate/latest.xpi"
    - "https://addons.mozilla.org/firefox/downloads/latest/wappalyzer/latest.xpi"
    - "https://addons.mozilla.org/firefox/downloads/latest/cookie-editor/latest.xpi"
    - "https://addons.mozilla.org/firefox/downloads/latest/simple-modify-header/latest.xpi"
    - "https://addons.mozilla.org/firefox/downloads/latest/retire-js/latest.xpi"
