---
- name: Create a directory
  ansible.builtin.file:
    path: "addons"
    state: directory
    mode: "0755"

- name: Download firefox addons
  ansible.builtin.get_url:
    url: "{{ item }}"
    dest: "addons/"
    mode: "0644"
  loop:
    - https://addons.mozilla.org/firefox/downloads/file/4228676/foxyproxy_standard-8.9.xpi
    - https://addons.mozilla.org/firefox/downloads/file/4098688/user_agent_string_switcher-0.5.0.xpi
    - https://addons.mozilla.org/firefox/downloads/file/4377180/deepl_translate-1.28.0.xpi
    - https://addons.mozilla.org/firefox/downloads/file/4413349/wappalyzer-6.10.77.xpi
    - https://addons.mozilla.org/firefox/downloads/file/4241002/cookie_editor-1.13.0.xpi
    - https://addons.mozilla.org/firefox/downloads/file/4319544/simple_modify_header-1.9.0.xpi
    - https://addons.mozilla.org/firefox/downloads/file/4425995/retire_js-2.1.3.xpi

# - name: Install firefox addons
#   ansible.builtin.shell:
#     cmd: "firefox *.xpi"
