---
- name: Add docker.list
  become: true
  become_method: ansible.builtin.sudo
  ansible.builtin.lineinfile:
    create: true
    line: "deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/debian bookworm stable"
    dest: /etc/apt/sources.list.d/docker.list
    mode: "0644"

- name: Import gpg key
  become: true
  become_method: ansible.builtin.sudo
  ansible.builtin.get_url:
    url: https://download.docker.com/linux/debian/gpg
    dest: /etc/apt/keyrings/docker.asc
    mode: "0644"

- name: Update apt repo/cache
  become: true
  become_method: ansible.builtin.sudo
  ansible.builtin.apt:
    update_cache: true
    force_apt_get: true

- name: Install docker-ce
  become: true
  become_method: ansible.builtin.sudo
  ansible.builtin.package:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io

- name: Download BloodHound CE docker compose yaml file
  become: true
  become_method: ansible.builtin.sudo
  ansible.builtin.get_url:
    url: https://ghst.ly/getbhce
    dest: /opt/BloodHound/docker-compose.yml
    mode: "0644"