---
- name: Install package[apt]
  ansible.builtin.include_tasks: package.yml
- name: Clone repository[github]
  ansible.builtin.include_tasks: clone.yml
- name: Download repository[github_release]
  ansible.builtin.include_tasks: release.yml
- name: Install docker
  ansible.builtin.include_tasks: docker.yml
- name: Execute other task
  ansible.builtin.include_tasks: other.yml
