---
- name: Download Golang
  become: true
  become_method: ansible.builtin.sudo
  ansible.builtin.get_url:
    url: https://go.dev/dl/go1.23.5.linux-amd64.tar.gz
    dest: /tmp/
    mode: "0644"

- name: Install Golang
  become: true
  become_method: ansible.builtin.sudo
  ansible.builtin.shell:
    cmd: "rm -rf /usr/local/go && tar -C /usr/local -xzf /tmp/go1.23.5.linux-amd64.tar.gz"

- name: Install RustScan
  become: true
  become_method: ansible.builtin.sudo
  ansible.builtin.apt:
    deb: https://github.com/RustScan/RustScan/releases/download/2.3.0/rustscan_2.3.0_amd64.deb
