---
- name: Copying terminal config[user]
  ansible.builtin.copy:
    src: "{{ role_path }}/files/.zshrc"
    dest: "{{ ansible_user_dir }}"
    mode: "0644"

- name: Copying terminal config[root]
  become: true
  become_method: ansible.builtin.sudo
  ansible.builtin.copy:
    src: "{{ role_path }}/files/.zshrc"
    dest: "/root/"
    mode: "0644"
